//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VEditor.rc
//
#define IDW_LIBTREEWND                  50
#define IDW_CHAINWND                    51
#define IDW_PATCHWND                    52
#define IDW_WKSVIEW                     53
#define IDC_LIBRARYTREE                 98
#define IDR_MAINFRAME                   99
#define IDD_ABOUTBOX                    100
#define IDB_PFILETOP                    101
#define IDB_PFILELEFT                   102
#define IDB_PFILERIGHT                  103
#define IDB_PFILEBOT                    104
#define IDB_VG88FONT                    105
#define IDB_CHAIN                       106
#define IDB_DIGIT                       107
#define IDB_LP                          119
#define IDB_CLAST                       120
#define IDB_MODST                       121
#define IDB_TELECASTER                  122
#define IDB_P90                         123
#define IDB_LIPS                        124
#define IDB_PAF                         125
#define IDB_RICK                        126
#define IDB_CHET                        127
#define IDB_SSH                         128
#define IDR_VEDITOTYPE                  129
#define IDB_VARIGUITAR                  129
#define IDB_ACOUSMIC                    130
#define IDB_ACOUSPIEZO                  131
#define IDB_ORGANB                      132
#define IDB_SOLO                        133
#define IDB_BOWED                       134
#define IDB_NYLONB                      135
#define IDB_PIPE                        136
#define IDB_AMPJC120                    137
#define IDB_AMPCLTWIN                   138
#define IDB_AMPCRUNCH                   139
#define IDB_AMPMATCH                    140
#define IDB_AMPVOX                      141
#define IDB_AMPBLUES                    142
#define IDB_AMPBG                       143
#define IDB_AMP1959I                    144
#define IDB_AMP1959II                   145
#define IDB_AMP1959I_II                 146
#define IDB_AMPSLDN                     147
#define IDB_AMP5150                     148
#define IDB_AMPMETAL                    149
#define IDB_AMPACOUS                    150
#define IDB_AMPJAZZCOMBO                151
#define IDB_AMPPROCRUNCH                152
#define IDB_AMPTWEED                    153
#define IDB_AMPSTACKCRUNCH              154
#define IDB_AMPVOLEAD                   155
#define IDB_AMPVOCLEAN                  156
#define IDB_AMPMATCHLEAD                157
#define IDB_AMPFATMATCH                 158
#define IDB_AMPBGDRIVE                  159
#define IDB_AMPBGRYTHM                  160
#define IDB_AMPMSHIGHGAIN               161
#define IDB_AMPR_FIERRED                162
#define IDB_AMPR_FIERORANGE             163
#define IDB_AMPR_FIERVINT               164
#define IDB_AMPDRIVESTACK               165
#define IDB_AMPLEADSTACK                166
#define IDB_AMPMETALSTACK               167
#define IDB_AMPMETALLEAD                168
#define IDB_EFFCOMPRESSOR               169
#define IDB_EFFLIMITER                  170
#define IDB_EFFAUTOWAH                  171
#define IDB_EFFWAH                      172
#define IDB_EFFEQ                       173
#define IDB_EFFHARMONIST                174
#define IDB_EFFPSHIFTER                 175
#define IDB_EFFFLANGER                  176
#define IDB_EFFPHASER                   177
#define IDB_EFFSEQ                      178
#define IDB_EFF2x2CHORUS                179
#define IDB_EFFTREMOLO                  180
#define IDB_EFFPAN                      181
#define IDB_EFFPDSHIFT                  182
#define IDB_EFFVIBRATO                  183
#define IDB_EFFDEFRETTER                184
#define IDB_EFFUNIV                     185
#define IDB_EFFDELAY                    186
#define IDB_EFFCHORUS                   187
#define IDB_EFFREVERB                   188
#define IDB_EFFNS                       189
#define IDB_EFFFV                       190
#define IDB_INSTDIST                    191
#define IDB_CABLE                       192
#define IDB_PICKUP                      193
#define IDB_CABLECORNER                 194
#define IDB_CABLEINTER                  195
#define IDB_CABLE2                      196
#define IDB_DISTCLAOD                   197
#define IDB_DISTTURBOOD                 198
#define IDB_DISTDS1                     199
#define IDB_DISTDS2                     200
#define IDB_DISTFUZZ                    201
#define IDB_DETUNE                      202
#define IDB_POLYOCTAVE                  203
#define IDB_SLOWGEAR                    204
#define IDB_TUNE                        205
#define IDB_CRYSTALB                    206
#define IDI_ICONVGVIEW                  207
#define IDI_ICONVG                      208
#define IDI_ICONVGLIB                   209
#define IDB_PANEL1                      210
#define IDB_GUITAR                      211
#define IDB_ACOUSG                      212
#define IDB_NYLON                       213
#define IDB_OPENTUNE                    214
#define IDB_12STRINGS                   215
#define IDB_PDSHIFT                     216
#define IDB_POLYDIST                    217
#define IDB_POLYCOMP                    218
#define IDB_POLYOCT                     219
#define IDB_POLYSG                      220
#define IDB_VIOLIN                      221
#define IDB_DUAL                        222
#define IDB_FILTEBASS                   223
#define IDB_FLUTE                       224
#define IDB_TRUMPET                     225
#define IDB_PWM                         226
#define IDB_CRYSTAL                     227
#define IDB_ORGAN                       228
#define IDB_BRASS                       229
#define IDB_NYLONII                     230
#define IDB_SITAR                       231
#define IDB_WAVESYNTH                   232
#define IDB_VEDITOR                     233
#define IDB_VLIB                        234
#define IDB_GK2A                        235
#define IDB_FADERH1                     236
#define IDB_PANELPAN                    237
#define IDB_BUTTON1                     238
#define IDB_LED1                        239
#define IDB_ABOUT                       240
#define IDB_KNOB3                       241
#define IDB_KNOB4                       242
#define IDB_PANELAMP                    243
#define IDB_PANELMIXER                  244
#define IDB_PANELPITCHSHIFT             245
#define IDB_PANELFV                     246
#define IDB_WAH2                        247
#define IDB_PANELNS                     248
#define IDB_PANELREVERB                 249
#define IDB_AMPLIFERS                   250
#define IDB_PANELCHORUS                 251
#define IDB_PANELDELAY                  252
#define IDB_PANELCOMPRESSOR             253
#define IDB_PANELEQUALIZER              254
#define IDB_PANELPEDALWAH               255
#define IDB_PANELAUTOWAH                256
#define IDB_PANELLIMITER                257
#define IDB_PANELVOLBMPKEY              258
#define IDB_PANELVIBRATO                259
#define IDB_PANELTREMOLO                260
#define IDB_PANELPANEFF                 261
#define IDB_PANELPDSHIFT                262
#define IDB_PANEL2x2CHORUS              263
#define IDB_PANELSUBEQ                  264
#define IDB_PANELPHASER                 265
#define IDB_PANELFLANGER                266
#define IDB_PANELHARMONIST              267
#define IDB_KEY                         268
#define IDB_KNOB6                       269
#define IDB_KNOB7                       270
#define IDB_SELECTOR                    271
#define IDB_PANELPICKUP                 272
#define IDB_GUITARS                     273
#define IDB_PANELBODY                   274
#define IDB_BODYTYPE                    275
#define IDB_PANELGT                     276
#define IDB_PANELPICKUPACOUS            277
#define IDB_PANELPICKUPNYLON            278
#define IDB_PANELPICKUPVARI             279
#define IDB_GUITARSACOUS                280
#define IDB_PICKUPTYPE1                 281
#define IDB_PICKUPTYPE2                 282
#define IDB_PICKUPPOS                   283
#define IDB_PICKUPSINGLE1               284
#define IDB_PICKUPSINGLE2               285
#define IDB_PICKUPDOUBLE1               286
#define IDB_PICKUPDOUBLE2               287
#define IDB_PANELBODYNYLON              288
#define IDB_PANELEMPTY                  289
#define IDB_LABELS                      290
#define IDB_PANELBOTTOM                 291
#define IDB_SECTION                     292
#define IDB_SEFFAUTOWAH                 293
#define IDB_SEFFCHORUS                  294
#define IDB_SEFFCOMP                    295
#define IDB_SEFFDELAY                   296
#define IDB_SEFFEQ                      297
#define IDB_SEFFFLANGER                 298
#define IDB_SEFFHARMO                   299
#define IDB_SEFFPAN                     300
#define IDB_SEFFPEDSHIFT                301
#define IDB_SEFFPEDWAH                  302
#define IDB_SEFFPHASER                  303
#define IDB_SEFFREVERB                  304
#define IDB_SEFFVIBRATO                 305
#define IDB_LBVGWin1                    306
#define IDB_LTVGWin1                    307
#define IDB_LVGWin1                     308
#define IDB_MBVGWin1                    309
#define IDB_MTVGWin1                    310
#define IDB_RTVGWin1                    311
#define IDB_RVGWin1                     312
#define IDB_RBVGWin1                    313
#define IDB_SEFFNS                      314
#define IDB_EQLABEL                     315
#define IDB_GUITARNYLON                 316
#define IDB_EMPTY                       317
#define IDB_ASSIGNGKVOL                 318
#define IDB_ASSIGNCTL                   319
#define IDB_ASSIGNGKS1S2                320
#define IDB_ASSIGNMIDI                  321
#define IDB_ASSIGNPEDAL                 322
#define IDB_POPUP                       323
#define IDB_SPEAKER                     324
#define IDB_MIC1                        325
#define IDB_MIC2                        326
#define IDB_ORGANSLIDER                 327
#define IDB_ORGANS                      328
#define IDB_EFFDIST                     329
#define IDB_FLUTE2                      330
#define IDB_VIOLON2                     331
#define IDB_CRYSTAL2                    332
#define IDB_TRUMPET2                    333
#define IDB_LABELPAN                    334
#define IDB_VGFONTBW                    335
#define IDB_BRASSB                      336
#define IDB_DUALS                       337
#define IDB_DUALB                       338
#define IDB_PPWM                        339
#define IDB_PPWMB                       340
#define IDD_DEVICE                      341
#define IDD_SENDPATCH                   342
#define IDB_VGSEND                      343
#define IDB_LCD                         344
#define IDB_GKFUNC                      345
#define IDB_DIAL                        346
#define IDB_TUNER                       347
#define IDB_OUTPUTSELECT                348
#define IDB_BUTTON2                     349
#define IDC_CURSOR                      350
#define IDC_CURSORMS                    351
#define IDC_CURSORMP                    352
#define IDC_CURSORMPS                   353
#define IDC_CURSORM                     354
#define IDB_GK2AB                       355
#define IDC_CURSORF                     355
#define IDB_VLIB2                       356
#define IDC_CURSORG                     356
#define IDB_NYLONIIB                    357
#define IDC_CURSORGP                    357
#define IDB_SITARB                      358
#define IDB_MSHIGHGAIN                  359
#define IDB_RECTIFIER                   360
#define IDB_LED2                        368
#define IDB_BUTTON3                     369
#define IDB_GUITARNYLONII               370
#define IDB_SEFFUNIV                    381
#define IDB_SEFFDEFRETTER               383
#define IDB_BUTTONSAVE                  384
#define IDB_BUTTONRENAME                385
#define IDB_BUTTONCOPY                  386
#define IDB_BUTTONDELETE                387
#define IDD_INPUT                       388
#define IDB_SITARP                      389
#define IDB_WAVESQUARE                  390
#define IDB_WAVE                        391
#define IDB_WAVESAW                     392
#define IDB_FILTERBASSS                 393
#define IDB_FILTERBASSB                 394
#define IDD_SENDPATCHFORM               395
#define IDB_DOWN                        397
#define IDB_UP                          398
#define IDD_LIBPROP                     399
#define IDB_VLIBB                       400
#define IDI_ICON1                       404
#define IDC_EQ_ONOFF                    1000
#define IDC_AMP_ONOFF                   1001
#define IDC_PANEL_AMP                   1002
#define IDC_PANEL_EFFECTS               1003
#define IDC_PANEL_LEVEL_BMP_KEY         1004
#define IDC_PANEL_PEDAL_ASSIGN          1005
#define IDC_PTSHIFT_ONOFF               1006
#define IDC_FV_VOLUME                   1007
#define IDC_DEVICETYPE                  1007
#define IDC_NS_ONOFF                    1008
#define IDC_DEVICENAME                  1008
#define IDC_REVERB_ONOFF                1009
#define IDC_DEVICEID                    1009
#define IDC_PROGRESS1                   1009
#define IDC_DELAY_ONOFF                 1010
#define IDC_ANIMATE                     1010
#define IDC_AUDITIONPATCH               1010
#define IDC_CHORUS_ONOFF                1011
#define IDC_POURCENT                    1011
#define IDC_COMP_ONOFF                  1012
#define IDC_MIDIINPUT                   1012
#define IDC_LABEL                       1012
#define IDC_WAH_ONOFF                   1013
#define IDC_MIDIOUTPUT                  1013
#define IDC_COSMEQ_ONOFF                1014
#define IDC_MOD_ONOFF                   1015
#define IDC_HARMONY1                    1016
#define IDC_NAME                        1016
#define IDC_HARMONY2                    1017
#define IDC_DIRLEVEL                    1018
#define IDC_FROM_PATCH                  1018
#define IDC_GT_ONOFF                    1019
#define IDC_TO_PATCH                    1019
#define IDC_PICKUPPOS                   1020
#define IDC_TO_PROGRAM                  1020
#define IDC_PICKUP                      1021
#define IDC_TITLE                       1021
#define IDC_PATCHLIST                   1022
#define IDC_SYSTEM                      1022
#define IDC_POCT_ONOFF                  1023
#define IDC_PANEL_ASSIGN                1024
#define IDC_FILE                        1024
#define IDC_ASSIGN_ONOFF                1025
#define IDC_POPUP                       1026
#define IDC_LIBNAME                     1026
#define IDC_POPUP_CANCEL                1027
#define IDC_FIRSTPATCH                  1027
#define IDC_POPUP_VALIDATE              1028
#define IDC_SEL_CHANGE                  1029
#define IDC_MIC                         1030
#define IDC_AMP_TYPE                    1031
#define IDC_ASSIGN_TARGET               1032
#define IDC_TUNE                        1033
#define IDC_DIST_ONOFF                  1034
#define IDB_PANEL3                      1035
#define IDB_PANEL2                      1036
#define IDB_FADERV1                     1037
#define IDB_SWITCH1                     1038
#define IDB_KNOB1                       1039
#define IDB_KNOB2                       1040
#define IDC_GLOBAL_ONOFF                1041
#define IDC_OUTPUT_SELECT               1042
#define IDC_SEND_MIDI                   1043
#define ID_LIBTREE                      32773
#define ID_CHAIN                        32774
#define ID_PATCHEDIT                    32775
#define ID_CASCAD                       32776
#define ID_TILEH                        32777
#define ID_TILEV                        32778
#define ID_APP_SETTINGS                 32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32782                  32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON32785                  32785
#define ID_OPEN                         32786
#define ID_SEND                         32788
#define ID_RECEIVE                      32789
#define ID_NEW                          32790
#define IDC_PRESET                      32791
#define IDC_PRESET_CANCEL               32792
#define IDC_PRESET_VALIDATE             32793
#define IDC_PRESETSAVE                  32794
#define IDC_PRESETCOPY                  32795
#define IDC_PRESETDELETE                32796
#define IDC_PRESETRENAME                32797
#define IDC_COSM_GT                     32798
#define ID_OPENVGWINDOW                 32799
#define ID_WINDOW_LIBRARY               32800
#define IDC_COMPARE                     32801
#define ID_DELETE                       32802
#define ID_SYNCHRONIZE                  32803
#define ID_SAVE                         32804
#define ID_SAVE_ALL                     32805
#define ID_PROPERTIES                   32806
#define ID_SEND_ONE_PATCH               32807
#define ID_CLOSE                        32808
#define ID_EDIT_DELETE                  32808
#define ID_SAVEAS                       32809
#define ID_EDIT_RENAME                  32810
#define ID_ORDER                        32811

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        405
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
